start: function_def* main_func

main_func : "task" "main" "()" "-" ">" ret_type "{" command* return_command "}"

ret_type: TYPE      -> return_type

command: variable_declaration ";"
    | allocation ";"
    | print_command ";"
    | function_call ";"
    | loop
    | conditional
    | "break" ";"
    | "continue" ";"

variable_declaration: "let" TYPE VAR "=" expr

allocation_aux: VAR ASS_OP expr
        | VAR "++"
        | VAR "--"


array_access: VAR "[" NUMBER "]"

allocation: VAR "=" expr
        | array_access "=" expr
        | allocation_aux
        
array_expr: "[" element_list? "]"

element_list: NUMBER ("," NUMBER)*


expr: VAR
    | NUMBER
    | STRING
    | function_call
    | expr OP expr
    | expr LOGICAL_OP expr
    | array_expr
    | array_access
    
print_command: "show" "(" VAR ")"
        | "show" "(" NUMBER ")"
        | "show" "(" STRING ")"
        | "show" "(" array_access ")"
        
function_def: "task" VAR "(" parametros? ")" "-" ">" TYPE "{" command* return_command "}"

return_command: "return" expr ";"

parametros: param "," parametros
    | param

param: TYPE VAR

function_call: VAR "(" arg_list? ")"

arg_list: expr "," arg_list
    | expr

foreach_loop: "foreach" "(" VAR "in" expr ")" "{" command* "}"

loop: for_loop | loop_loop | foreach_loop

for_loop: "for" "(" variable_declaration ";" for_cond ";" for_update ")" "{" command* "}" 

for_cond: bool_expr

for_update: allocation_aux

loop_loop: "loop" "(" bool_expr ")" "{" command* "}"

conditional: check_command | match_command

check_command: "check" "(" bool_expr ")" "{" command* "}" (also_command)* (otherwise_command)?

also_command: "also" "(" bool_expr ")" "{" command* "}"

otherwise_command: "otherwise" "{" command* "}"

match_command: "match" "(" expr ")" "{" option_command* standard_command? "}"

option_command: "option" expr ":" command*

standard_command: "standard" ":" command*

bool_expr: expr LOGICAL_OP expr
    | function_call

TYPE: "int" | "double" | "tuple" | "string" | "array" | "bool" | "void"

VAR: /[a-z]+(_[a-z]+)*/

NUMBER: /-?\\d+(\\.\\d+)?/

STRING: /".*"/

OP: "+" | "-" | "*" | "/"

LOGICAL_OP: "==" | "!=" | "<=" | ">=" | "<" | ">"

ASS_OP: "+=" | "-=" | "*=" | "/="

%import common.WS
%ignore WS
